package com.singularitycoder.connectme.helpers.constants

object Preferences {
    const val PREFERENCE_STORAGE_NAME = "connect_me_preferences"

    const val KEY_OPEN_AI_API_SECRET = "KEY_OPEN_AI_API_SECRET"
    const val KEY_OPEN_AI_MODEL = "KEY_OPEN_AI_MODEL"

    const val KEY_SEARCH_SUGGESTION_PROVIDER = "KEY_SEARCH_SUGGESTION_PROVIDER"
    const val KEY_ENABLE_VPN = "KEY_ENABLE_VPN"
    const val KEY_ENABLE_AD_BLOCKER = "KEY_ENABLE_AD_BLOCKER"
    const val KEY_ENABLE_JAVASCRIPT = "KEY_ENABLE_JAVASCRIPT"
    const val KEY_ENABLE_JAVASCRIPT_OPEN_WINDOWS_AUTO = "KEY_ENABLE_JAVASCRIPT_OPEN_WINDOWS_AUTO"
    const val KEY_ENABLE_GEOLOCATION = "KEY_ENABLE_GEOLOCATION"
    const val KEY_DO_NOT_TRACK = "KEY_DO_NOT_TRACK"
}